"""
    AbstractHSMM

Abstract supertype for a Hidden Semi-Markov Model amenable to simulation, inference and learning.

Unlike [`AbstractHMM`](@ref), an `AbstractHSMM` explicitly models state durations through a per-state
[`AbstractDurationDistribution`](@ref). Self-transitions are forbidden, since each sojourn duration
is generated by the duration distribution attached to the state being entered.

# Interface

To create your own subtype of `AbstractHSMM`, you need to implement:

- [`initialization`](@ref)
- [`transition_matrix`](@ref)
- [`obs_distributions`](@ref)
- [`duration_distributions`](@ref)
- [`fit!`](@ref) (for learning)

# Applicable functions

Any `AbstractHSMM` which satisfies the interface can be given to the following functions:

- [`rand`](@ref)
- [`logdensityof`](@ref)
- [`forward`](@ref)
- [`viterbi`](@ref)
- [`forward_backward`](@ref)
- [`baum_welch`](@ref) (if `fit!` is implemented)

!!! note
    `AbstractHSMM` is intentionally **not** a subtype of [`AbstractHMM`](@ref). Although every HMM is
    mathematically an HSMM with geometric durations, making `AbstractHSMM <: AbstractHMM` would cause
    HMM-only methods (which ignore duration distributions) to silently dispatch on HSMMs and produce
    incorrect results. Sibling supertypes keep dispatch explicit.
"""
abstract type AbstractHSMM end

@inline DensityInterface.DensityKind(::AbstractHSMM) = HasDensity()

## Interface

"""
    length(hsmm)

Return the number of states of `hsmm`.
"""
Base.length(hsmm::AbstractHSMM) = length(initialization(hsmm))

"""
    eltype(hsmm, obs, control)

Return a type that can accommodate forward-backward computations for `hsmm` on observations similar to `obs`.

It is typically a promotion between the element type of the initialization, the element type of the
transition matrix, and the type of an observation logdensity evaluated at `obs`.
"""
function Base.eltype(hsmm::AbstractHSMM, obs, control)
    init_type = eltype(initialization(hsmm))
    trans_type = eltype(transition_matrix(hsmm, control))
    dist = obs_distributions(hsmm, control)[1]
    logdensity_type = typeof(logdensityof(dist, obs))
    return promote_type(init_type, trans_type, logdensity_type)
end

"""
    duration_distributions(hsmm)
    duration_distributions(hsmm, control)

Return a vector of duration distributions, one for each state of `hsmm` (possibly when `control` is applied).

Each duration distribution should implement:

- `Random.rand(rng, dist)` for sampling positive-integer durations
- `DensityInterface.logdensityof(dist, k::Int)` for `log P(D = k)`
- `StatsAPI.fit!(dist, durations, weights)` for learning

See [`AbstractDurationDistribution`](@ref).
"""
function duration_distributions end

## Fallbacks for no control

transition_matrix(hsmm::AbstractHSMM, ::Nothing) = transition_matrix(hsmm)
log_transition_matrix(hsmm::AbstractHSMM, ::Nothing) = log_transition_matrix(hsmm)
obs_distributions(hsmm::AbstractHSMM, ::Nothing) = obs_distributions(hsmm)
duration_distributions(hsmm::AbstractHSMM, ::Nothing) = duration_distributions(hsmm)

log_initialization(hsmm::AbstractHSMM) = elementwise_log(initialization(hsmm))

function log_transition_matrix(hsmm::AbstractHSMM, control)
    return elementwise_log(transition_matrix(hsmm, control))
end

## Prior

DensityInterface.logdensityof(hsmm::AbstractHSMM) = false

## Sampling

"""
    rand([rng,] hsmm::AbstractHSMM, T)
    rand([rng,] hsmm::AbstractHSMM, control_seq)

Simulate `hsmm` for `T` time steps, or when the sequence `control_seq` is applied.

Sojourn lengths are drawn from the model's duration distributions, so consecutive timesteps share the
same state until the duration elapses (after which a new state is drawn under the no-self-transition
constraint).

Return a named tuple `(; state_seq, obs_seq, duration_seq)`, where `duration_seq[t]` is the duration
originally sampled for the sojourn containing `t` (it may exceed the actual sojourn length if the
sequence was truncated at `T`).
"""
function Random.rand(rng::AbstractRNG, hsmm::AbstractHSMM, control_seq::AbstractVector)
    T = length(control_seq)
    N = length(hsmm)

    init = initialization(hsmm)
    dummy_log_probas = fill(-Inf, N)
    current_state = rand(rng, LightCategorical(init, dummy_log_probas))

    obs_dists1 = obs_distributions(hsmm, control_seq[1])
    first_obs = rand(rng, obs_dists1[current_state])

    state_seq = Vector{Int}(undef, T)
    obs_seq = Vector{typeof(first_obs)}(undef, T)
    duration_seq = Vector{Int}(undef, T)

    t = 1
    while t <= T
        duration_dists = duration_distributions(hsmm, control_seq[t])
        current_duration = rand(rng, duration_dists[current_state])

        end_time = min(t + current_duration - 1, T)
        for τ in t:end_time
            state_seq[τ] = current_state
            duration_seq[τ] = current_duration
            if τ == 1
                obs_seq[τ] = first_obs
            else
                obs_dists = obs_distributions(hsmm, control_seq[τ])
                obs_seq[τ] = rand(rng, obs_dists[current_state])
            end
        end

        t = end_time + 1

        if t <= T
            trans = transition_matrix(hsmm, control_seq[t - 1])
            current_state = rand(
                rng, LightCategorical(trans[current_state, :], dummy_log_probas)
            )
        end
    end

    return (; state_seq=state_seq, obs_seq=obs_seq, duration_seq=duration_seq)
end

function Random.rand(hsmm::AbstractHSMM, control_seq::AbstractVector)
    return rand(default_rng(), hsmm, control_seq)
end

function Random.rand(rng::AbstractRNG, hsmm::AbstractHSMM, T::Integer)
    return rand(rng, hsmm, Fill(nothing, T))
end

function Random.rand(hsmm::AbstractHSMM, T::Integer)
    return rand(hsmm, Fill(nothing, T))
end
