name: Run benchmarks

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]

# Only trigger the benchmark job when you add `run benchmark` label to the PR
jobs:
  Benchmark:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    if: contains(github.event.pull_request.labels.*.name, 'run benchmark')
    env:
      JULIA_NUM_THREADS: auto
      OPENBLAS_NUM_THREADS: "1"
    steps:
      - uses: MilesCranmer/AirspeedVelocity.jl@action-v1
        with:
          julia-version: "1"
          tune: "true"
          bench-on: ${{ github.event.pull_request.head.sha }}
